### ISSUE TITLE
compare two vcf files

### ISSUE THREAD

**Issue by silvius76** [Clinical-Genomics/genotype#19]
Hi,

I read that taboo can compare vcf files,

I run:

taboo compare file*.sorted.vcf > diff.txt

But "compare" option dosen't exist
I saw in man page...but nothing

I need check only different contacts between two vcf
Is it poossible ?

Thanks

**Comment by robinandeer** [comment]
Genotype can compare genotype calls from two separate sources

But it's not possible of within the range of the software to do more generalized comparisons between VCF files.
