### ISSUE TITLE
Bug(incorrect matching of data)

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/genotype#68]
We recently discovered a case where the variants were told to be mismatched by the UI which was also confirmed by using the `genotype check` CLI command. 

However, when we investigated these variants further we found that:

- The sample was Homozygous (0 reads supporting REF) for ALT
- The sample was Homozygous for ALT in both MAF and Sequence data
-  The positions of concern are on different chromosomes and are not a specific base.

This is very concerning - as it would seem that either the data uploaded to Genotype is not what we believe it to be OR we are doing an incorrect match for these Homozygous calls.

**Comment by Vince-janv** [comment]
Issue caused by demux using wrong sample sheet, and hence reads from multiple samples. Hence genotype is functioning correctly. Overwrite the previous data using `cg upload genotypes <case_id> -f`
